{
	"version": 1554519509,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/jugador-sheet0.png",
		"images/dirt-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/nubes.png",
		"images/sprite6-sheet0.png",
		"images/point-sheet0.png",
		"images/fondodehistoria.png",
		"images/posiblefoe-sheet0.png",
		"images/water-sheet0.png",
		"images/win-sheet0.png",
		"images/spritefont.png",
		"images/bordes-sheet0.png",
		"images/guardian-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite4-sheet0.png",
		"images/tiledbackground4.png",
		"images/tiledbackground6.png",
		"images/sprite7-sheet0.png",
		"images/limiteguardian-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"media/give it away [8 bit tribute to red hot chili peppers] - 8 bit universe.m4a",
		"media/give it away [8 bit tribute to red hot chili peppers] - 8 bit universe.ogg",
		"media/feel good inc. [8 bit tribute to gorillaz] - 8 bit universe.m4a",
		"media/feel good inc. [8 bit tribute to gorillaz] - 8 bit universe.ogg",
		"media/19-2000 [8 bit universe tribute to gorillaz].m4a",
		"media/19-2000 [8 bit universe tribute to gorillaz].ogg",
		"media/hypnotize [8 bit tribute to system of a down] - 8 bit universe.m4a",
		"media/hypnotize [8 bit tribute to system of a down] - 8 bit universe.ogg",
		"media/stage 1 castlevania (nes) music.m4a",
		"media/stage 1 castlevania (nes) music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}